-- 보드 테이블 정보
CREATE TABLE BOARD (
   BOARD_NO NUMBER(11) PRIMARY KEY,
   title VARCHAR2(200),
   content CLOB,
   REG_NO NUMBER(11),
   REG_DT VARCHAR2(14),
   MOD_DT VARCHAR2(14),
   VIEWS NUMBER(11) DEFAULT 0
 );

-- 시퀀스
CREATE SEQUENCE SEQ_TB_BOARD_IDX
START WITH 1
INCREMENT BY 1
NOCACHE
NOCYCLE;

-- 회원
CREATE TABLE USERS (
   EMAIL VARCHAR2(30),
   PW VARCHAR2(30)
 );
-- 회원 정보
  INSERT INTO USERS (
			EMAIL,
			PW
		) VALUES (
			'hgal8877@gmail.com',
            '1111'
		);